server:
   address: localhost
   port: 9300
logging:
   config: classpath:log4j2.xml

spring:
   dataSource:
      gateway:
         driverClassName: com.mysql.jdbc.Driver
         url: jdbc:mysql://127.0.0.1:3306/gateway?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
         username: root
         password: root
         initialSize: 20
         minIdle: 5
         maxActive: 30
         maxWait: 30000
         removeAbandoned: true
         removeAbandonedTimeoutMillis: 300000
         defaultAutoCommit: false
         timeBetweenEvictionRunsMillis: 60000
         minEvictableIdleTimeMillis: 300000
         validationQuery: SELECT 1
         testWhileIdle: true
         connectionInitSql: set names utf8mb4
   cloud:
      consul:
        host: 192.168.0.112
        port: 8500
        discovery:
          register: false

zuul:
  routes:
     api:
       path: /api/**
       service-id: consul-miya